// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRPQkRJvjupCDWrYZAysuGjMT0_VSjLE',
    appId: '1:1020700791183:web:430e17d34701f8fbb37bfa',
    messagingSenderId: '1020700791183',
    projectId: 'tesfcm-78c93',
    authDomain: 'tesfcm-78c93.firebaseapp.com',
    storageBucket: 'tesfcm-78c93.appspot.com',
    measurementId: 'G-D4BLRC3NZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU77fBXHD2hRuPYa8D09bYyXshHEcQiwA',
    appId: '1:1020700791183:android:2d34dd7f0c1d5624b37bfa',
    messagingSenderId: '1020700791183',
    projectId: 'tesfcm-78c93',
    storageBucket: 'tesfcm-78c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnDAKaPEsfPj7rmShByWva2qVD3Y8DWc',
    appId: '1:1020700791183:ios:d0c24ca53a5be462b37bfa',
    messagingSenderId: '1020700791183',
    projectId: 'tesfcm-78c93',
    storageBucket: 'tesfcm-78c93.appspot.com',
    iosBundleId: 'com.example.flutterfcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnDAKaPEsfPj7rmShByWva2qVD3Y8DWc',
    appId: '1:1020700791183:ios:abf76d40afbfec33b37bfa',
    messagingSenderId: '1020700791183',
    projectId: 'tesfcm-78c93',
    storageBucket: 'tesfcm-78c93.appspot.com',
    iosBundleId: 'com.example.flutterfcm.RunnerTests',
  );
}
